FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json

COPY ./apps/ws-backend ./apps/ws-backend

RUN pnpm install

RUN npm run db:migrate

EXPOSE 8082

CMD ["npm", "run", "start:ws-backend"]
