FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web


RUN pnpm install

RUN npm run db:migrate

EXPOSE 3000

CMD ["npm", "run", "start:frontend"]
